---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ubuntu2204
    image: ubuntu:22.04
    pre_build_image: false
  - name: ubuntu2404
    image: ubuntu:24.04
    pre_build_image: false
provisioner:
  name: ansible
  config_options:
    defaults:
      inject_facts_as_vars: false
  inventory:
    host_vars:
      ubuntu2204:
        ansible_python_interpreter: /usr/bin/python3
      ubuntu2404:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: default
verifier:
  name: ansible
