---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts['distribution'] == 'Ubuntu'
      become: true

    - name: Install cron on RedHat
      ansible.builtin.dnf:
        name: cronie
        state: present
      when: ansible_facts['os_family'] == 'RedHat'
      become: true

    - name: Install required packages
      ansible.builtin.package:
        name:
          - zip
          - unzip
        state: present
      become: true
